export default function Education() {
    return (React.createElement("main", null,
        React.createElement("section", { className: "title" },
            React.createElement("h1", null, "EDUCATION"),
            React.createElement("h2", null, "Boston University (BU), Boston, MA"),
            React.createElement("p", null,
                React.createElement("strong", null, "Degree:"),
                " Bachelor of Arts in Computer Science"),
            React.createElement("p", null,
                React.createElement("strong", null, "Minor:"),
                " Business Administration and Management"),
            React.createElement("p", null,
                React.createElement("strong", null, "Graduation Date:"),
                " May 2025"),
            React.createElement("h3", null, "Subjects of Interest:"),
            React.createElement("ul", null,
                React.createElement("li", null, "Data Structures and Algorithms"),
                React.createElement("li", null, "Database Systems"),
                React.createElement("li", null, "Web Development"),
                React.createElement("li", null, "Data Analytics"),
                React.createElement("li", null, "Machine Learning"),
                React.createElement("li", null, "Business Management"),
                React.createElement("li", null, "Product Management")),
            React.createElement("p", null, "During my time at Boston University, I have developed a solid foundation in computer science principles and gained business management skills, which have prepared me for diverse technical roles in the industry. I have been involved in various academic projects and have taken courses that emphasize both technical and business-oriented problem-solving skills."))));
}
;
