export default function Home() {
    return (React.createElement("main", { className: "title" },
        React.createElement("section", null,
            React.createElement("section", { className: "about" },
                React.createElement("h3", null, "ABOUT ME"),
                React.createElement("h2", null, "Hi I\u2019m"),
                React.createElement("h1", null, "Arufa Khanom"),
                React.createElement("p", { className: "tagline" }, "Student / Computer Science / Business Administration"),
                React.createElement("div", { className: "about-details" },
                    React.createElement("div", { className: "left-column" },
                        React.createElement("img", { src: "/images/profile.jpg", alt: "Arufa Khanom", className: "profile-pic" }),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Hometown:"),
                            " Dhaka, Bangladesh"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Location:"),
                            " Redmond, WA"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Major:"),
                            " Computer Science"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Minor:"),
                            " Business Administration & Management")),
                    React.createElement("div", { className: "right-column" },
                        React.createElement("p", null,
                            "Hi, I\u2019m Arufa Khanom (pronounced ah-roo-fah), currently a senior at Boston University, majoring in Computer Science with a minor in Business Administration. My academic journey and hands-on experiences have equipped me with a unique intersection of technical expertise and business insight.",
                            React.createElement("br", null),
                            React.createElement("br", null),
                            "From leading a machine learning project on predicting movie revenue to integrating APIs into fully functional websites, I\u2019ve developed a passion for solving real-world business challenges through innovative tech solutions. With proficiency in Python, Java, React, and SQL, I enjoy taking on complex problems and collaborating with dynamic teams to create impactful, scalable solutions.",
                            React.createElement("br", null),
                            React.createElement("br", null),
                            "What sets me apart is my drive to bridge the gap between technology and business. I am passionate about leveraging data-driven insights and tech tools to enhance decision-making and optimize processes in ever-evolving industries. Whether it's automating workflows or building intuitive user experiences, I am constantly motivated by the prospect of making a meaningful difference.",
                            React.createElement("br", null),
                            React.createElement("br", null),
                            "Outside of coding, you\u2019ll likely find me experimenting with new recipes in the kitchen, planning my next travel adventure, or exploring hiking trails in the Pacific Northwest!")))))));
}
;
