import React from 'react';
import Calculator from './Calculator'; // Import the Calculator component
export default function Projects() {
    return (React.createElement("main", null,
        React.createElement("section", { className: "title" },
            React.createElement("h1", null, "Projects"),
            React.createElement("section", null,
                React.createElement("h2", null, "Movie Revenue Predictor"),
                React.createElement("p", null,
                    React.createElement("strong", null, "Tools:"),
                    " Python, Jupyter Notebook, Kaggle Dataset (TMDB)"),
                React.createElement("ul", null,
                    React.createElement("li", null, "Accomplished a 15% reduction in mean squared error compared to baseline models by developing and optimizing a machine learning model to predict movie revenue, incorporating features such as actor/director success, release season, and budget."),
                    React.createElement("li", null, "Improved model performance through the use of Boosted Decision Trees and other optimization techniques, enhancing predictive accuracy.")),
                React.createElement("a", { className: "btn", href: "https://github.com/arufak/PredictingMovieRevenue", target: "_blank", rel: "noopener noreferrer" },
                    React.createElement("i", { className: "fab fa-github" }),
                    " View on GitHub")),
            React.createElement("section", null,
                React.createElement("h2", null, "ThatsAWrap - Functional Website using Spotify API"),
                React.createElement("p", null,
                    React.createElement("strong", null, "Tools:"),
                    " Python, HTML, JavaScript, CSS, MongoDB, Spotify API"),
                React.createElement("ul", null,
                    React.createElement("li", null, "Accomplished increased user engagement by developing an interactive web application that provides personalized monthly top 10 song lists, leveraging the Spotify API for real-time updates."),
                    React.createElement("li", null, "Enhanced user experience with a responsive and user-friendly interface built using JavaScript, CSS, and HTML, while achieving seamless account management and personalized content delivery through efficient MongoDB integration.")),
                React.createElement("a", { className: "btn", href: "https://github.com/arufak/ThatsAWrap", target: "_blank", rel: "noopener noreferrer" },
                    React.createElement("i", { className: "fab fa-github" }),
                    " View on GitHub")),
            React.createElement("section", null,
                React.createElement("h2", null, "Notes Web App"),
                React.createElement("p", null,
                    React.createElement("strong", null, "Tools:"),
                    " Python, Flask, SQLAlchemy, JavaScript"),
                React.createElement("ul", null,
                    React.createElement("li", null, "Accomplished secure user note management by building a web application that allows users to sign up, log in, and log out, ensuring that only authenticated users can access or modify their notes."),
                    React.createElement("li", null, "Enhanced security and data integrity by utilizing Flask for backend development and SQLAlchemy for database management, ensuring secure data storage with user-specific access control through foreign key relationships.")),
                React.createElement("a", { className: "btn", href: "https://github.com/arufak/Flask-Web-App", target: "_blank", rel: "noopener noreferrer" },
                    React.createElement("i", { className: "fab fa-github" }),
                    " View on GitHub")),
            React.createElement("section", null,
                React.createElement("h2", null, "Spotify Data Analysis"),
                React.createElement("p", null,
                    React.createElement("strong", null, "Tools:"),
                    " Python, Amazon AWS S3, AWS QuickSight, Jupyter Notebook"),
                React.createElement("ul", null,
                    React.createElement("li", null, "Accomplished detailed insights into artist popularity and song characteristics as measured by comprehensive visualizations in AWS QuickSight by analyzing the Spotify dataset using data stored and managed in Amazon S3."),
                    React.createElement("li", null, "Increased understanding of music trends by developing interactive dashboards that visualized metrics like artist song count, time signature distribution, energy-valence correlation, and danceability-popularity relationships, providing actionable insights for music industry trends.")),
                React.createElement("a", { className: "btn", href: "https://github.com/arufak/Spotify-Data-Analysis", target: "_blank", rel: "noopener noreferrer" },
                    React.createElement("i", { className: "fab fa-github" }),
                    " View on GitHub")),
            React.createElement("section", null,
                React.createElement("h2", null, "Simple Calculator"),
                React.createElement("p", null,
                    React.createElement("strong", null, "Tools:"),
                    " HTML, CSS, JavaScript"),
                React.createElement("ul", null,
                    React.createElement("li", null, "A basic calculator that performs addition, subtraction, multiplication, division, exponentiation (using a for loop), and clearing results."),
                    React.createElement("li", null, "The result is displayed in red if it is negative.")),
                React.createElement(Calculator, null),
                " "))));
}
;
