export default function Skills() {
    return (React.createElement("main", { className: "title" },
        React.createElement("section", null,
            React.createElement("h1", null, "SKILLS"),
            React.createElement("h2", null, "Technical Skills"),
            React.createElement("ul", null,
                React.createElement("li", null,
                    React.createElement("strong", null, "Programming Languages:"),
                    " Python, Java, JavaScript, Go"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Web Development:"),
                    " HTML, CSS, React, Flask"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Databases:"),
                    " SQL, MongoDB, SQLAlchemy"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Cloud Computing:"),
                    " AWS (Amazon Web Services)"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Other Tools:"),
                    " Git, Excel")),
            React.createElement("h2", null, "Relevant Skills"),
            React.createElement("ul", null,
                React.createElement("li", null,
                    React.createElement("strong", null, "Machine Learning:"),
                    " Experience with Boosted Decision Trees and model optimization"),
                React.createElement("li", null,
                    React.createElement("strong", null, "API Integration:"),
                    " Spotify API for building interactive web apps"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Responsive Design:"),
                    " Building user-friendly and responsive web interfaces"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Project Management:"),
                    " Leadership experience in managing projects from inception to deployment")),
            React.createElement("h2", null, "Languages"),
            React.createElement("ul", null,
                React.createElement("li", null,
                    React.createElement("strong", null, "Bengali:"),
                    " Fluent"),
                React.createElement("li", null,
                    React.createElement("strong", null, "English:"),
                    " Fluent"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Hindi:"),
                    " Conversational"),
                React.createElement("li", null,
                    React.createElement("strong", null, "Urdu:"),
                    " Conversational")))));
}
;
